# This file defines the steps for Google Cloud Build to automatically deploy your function.
steps:
  # Step 1: Install Node.js dependencies
  # This step runs 'npm install' in your function's directory to prepare it for deployment.
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'backend/functions/image-handler' # The directory where your code is located

  # Step 2: Deploy the function
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'functions'
      - 'deploy'
      # The public name of the function, which determines its URL.
      - 'updateProductImage'
      - '--gen2'
      - '--runtime=nodejs22'
      - '--region=asia-south1'
      - '--source=backend/functions/image-handler' # The directory containing the code
      # This correctly points to the 'handleImageUpload' export in your index.js file.
      - '--entry-point=handleImageUpload'
      - '--trigger-http'
      - '--allow-unauthenticated'
      # Set environment variables from Cloud Build substitution variables.
      # You must configure these (e.g., _MONGO_URI) in your Cloud Build trigger settings.
      - '--set-env-vars=MONGO_URI=$_MONGO_URI,JWT_SECRET=$_JWT_SECRET,GCS_BUCKET_NAME=$_GCS_BUCKET_NAME,FRONTEND_URL=$_FRONTEND_URL'

options:
  logging: CLOUD_LOGGING_ONLY

