steps:
  # Step 1: Explicitly run 'npm install' inside your function's directory.
  # Assuming the function code is located in 'backend/functions/deliveryagent_profile'.
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'backend/functions/deliveryagent_profile'

  # Step 2: Deploy the delivery agent profile function.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'functions'
      - 'deploy'
      - 'deliveryagent-profile' # Function name
      - '--gen2'
      - '--runtime=nodejs22'
      - '--region=asia-south1' # Keep your desired region
      - '--source=./backend/functions/deliveryagent_profile'
      - '--entry-point=deliveryagent_profile_update' # This matches the export name in the rectified index.js
      - '--trigger-http'
      - '--allow-unauthenticated' # Use authentication middleware to enforce security
      - '--set-env-vars=MONGO_URI=$_MONGO_URI,JWT_SECRET=$_JWT_SECRET

options:
  logging: CLOUD_LOGGING_ONLY
