# In your cloudbuild.yaml 'steps' section
steps:
  # --- Deploy the 'updateProductImage' function ---
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'functions'
      - 'deploy'
      - 'updateProductImage' # The name of the exported function in index.js
      - '--gen2'
      - '--runtime=nodejs22'
      - '--region=asia-south1'
      - '--source=backend/functions/updateProductImage' # The directory containing the code
      - '--entry-point=updateProductImage' # The name of the export
      - '--trigger-http'
      - '--allow-unauthenticated'
      - '--timeout=300s'            # ✅ INCREASED TIMEOUT: Gives the function 5 minutes to complete
      - '--memory=512MB'
      - '--set-env-vars=MONGO_URI=$_MONGO_URI,JWT_SECRET=$_JWT_SECRET,GCS_BUCKET_NAME=$_GCS_BUCKET_NAME'
options:
  logging: CLOUD_LOGGING_ONLY