# This file defines the steps for Google Cloud Build to automatically deploy your function.
steps:
  # Step 1: Install Node.js dependencies
  # This step runs 'npm install' in your function's directory to prepare it for deployment.
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    # 'dir' specifies the directory where your function's code is located.
    # Update this path if your folder structure is different.
    dir: 'backend/functions/image-handler'

  # Step 2: Deploy the function to Google Cloud Functions
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'functions'
      - 'deploy'
      # The name of the deployed function. Let's name it to match the export.
      - 'handleImageUpload'
      - '--gen2'
      - '--runtime=nodejs22'
      - '--region=asia-south1'
      # The directory containing the code and node_modules.
      - '--source=backend/functions/image-handler'
      # The name of the export in your index.js file (e.g., exports.handleImageUpload = app).
      - '--entry-point=handleImageUpload'
      - '--trigger-http'
      - '--allow-unauthenticated'
      # Set environment variables from Cloud Build substitution variables.
      # You must configure these (e.g., _MONGO_URI) in your Cloud Build trigger settings.
      - '--set-env-vars=MONGO_URI=$_MONGO_URI,JWT_SECRET=$_JWT_SECRET,GCS_BUCKET_NAME=$_GCS_BUCKET_NAME,FRONTEND_URL=$_FRONTEND_URL'

# Optional: Configure logging for the build process itself.
options:
  logging: CLOUD_LOGGING_ONLY
