steps:
  # --- Step 1: Copy common code into the function's directory ---
  # This is the new step that fixes the import errors
  - name: 'alpine' # <-- This is the fix. 'alpine' is a valid, lightweight image with 'cp'
    entrypoint: 'cp'
    args:
      - '-r' # Recursive copy
      - 'backend/functions/common' # The source directory to copy
      - 'backend/functions/shop_products/common' # The destination inside the function's folder

  # --- Step 2: Install dependencies ---
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'backend/functions/shop_products'

  # --- Step 3: Deploy the shop_products function ---
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'shop_products'
      - '--gen2'
      - '--runtime=nodejs22'
      - '--region=asia-south1'
      - '--source=backend/functions/shop_products' # Removed './' for best practice
      - '--entry-point=shop_products'
      - '--trigger-http'
      - '--allow-unauthenticated'
      # Correct, single-line env vars
      - '--set-env-vars=MONGO_URI=$_MONGO_URI,JWT_SECRET=$_JWT_SECRET,GCS_BUCKET_NAME=$_GCS_BUCKET_NAME'

options:
  logging: CLOUD_LOGGING_ONLY

