steps:
  # Deploy ONLY the 'customer-profile' function
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'functions'
      - 'deploy'
      - 'customer-profile'
      - '--gen2'
      - '--runtime=nodejs22'
      - '--region=asia-south1'
      - '--source=./backend/functions/customer_profile'
      - '--entry-point=customer_profile'
      - '--trigger-http'
      - '--allow-unauthenticated'
      - '--set-env-vars=MONGO_URI=$_MONGO_URI,JWT_SECRET=$_JWT_SECRET'

options:
  logging: CLOUD_LOGGING_ONLY